// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TG_DETAIL_ODB_HXX
#define TG_DETAIL_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "tg_detail.hpp"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // tg_detail
  //
  template <>
  struct class_traits< ::tg_detail >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::tg_detail >
  {
    public:
    typedef ::tg_detail object_type;
    typedef ::tg_detail* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // tg_detail
  //
  template <typename A>
  struct query_columns< ::tg_detail, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // tgid
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::int64_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    tgid_type_;

    static const tgid_type_ tgid;

    // username
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    username_type_;

    static const username_type_ username;

    // first_name
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    first_name_type_;

    static const first_name_type_ first_name;

    // last_name
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    last_name_type_;

    static const last_name_type_ last_name;

    // language_code
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    language_code_type_;

    static const language_code_type_ language_code;

    // is_bot
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    is_bot_type_;

    static const is_bot_type_ is_bot;

    // user_id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    user_id_type_;

    static const user_id_type_ user_id;
  };

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::id_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::tgid_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  tgid (A::table_name, "\"tgid\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::username_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  username (A::table_name, "\"username\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::first_name_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  first_name (A::table_name, "\"first_name\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::last_name_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  last_name (A::table_name, "\"last_name\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::language_code_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  language_code (A::table_name, "\"language_code\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::is_bot_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  is_bot (A::table_name, "\"is_bot\"", 0);

  template <typename A>
  const typename query_columns< ::tg_detail, id_sqlite, A >::user_id_type_
  query_columns< ::tg_detail, id_sqlite, A >::
  user_id (A::table_name, "\"user_id\"", 0);

  template <typename A>
  struct pointer_query_columns< ::tg_detail, id_sqlite, A >:
    query_columns< ::tg_detail, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::tg_detail, id_sqlite >:
    public access::object_traits< ::tg_detail >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // tgid_
      //
      long long tgid_value;
      bool tgid_null;

      // username_
      //
      details::buffer username_value;
      std::size_t username_size;
      bool username_null;

      // first_name_
      //
      details::buffer first_name_value;
      std::size_t first_name_size;
      bool first_name_null;

      // last_name_
      //
      details::buffer last_name_value;
      std::size_t last_name_size;
      bool last_name_null;

      // language_code_
      //
      details::buffer language_code_value;
      std::size_t language_code_size;
      bool language_code_null;

      // is_bot_
      //
      long long is_bot_value;
      bool is_bot_null;

      // user_id_
      //
      long long user_id_value;
      bool user_id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::tg_detail, id_common >:
    public access::object_traits_impl< ::tg_detail, id_sqlite >
  {
  };

  // tg_detail
  //
}

#include "tg_detail-odb.ixx"

#include <odb/post.hxx>

#endif // TG_DETAIL_ODB_HXX
