name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
    - name: cmake configure
      working-directory: ./telebot
      run: CXXFLAGS=--std=c++14 cmake -B '${{ github.workspace }}/build' -S '${{ github.workspace }}/telebot/' -DCMAKE_TOOLCHAIN_FILE='${{ github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=YE
    - name: make
      working-directory: ./build
      run: make
    - name: make check
      working-directory: ./build
      run: make check
    - name: make distcheck
      working-directory: ./build
      run: make distcheck
